apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-app-controller
  labels:
    app: flask-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: custom-container
          image: manthan190698/flask-app
          ports:
          - name: nodejs-port
            containerPort: 5000