apiVersion: v1
kind: Service
metadata: 
  name: flask-app-service
spec:
  ports:
  - port: 31003
    nodePort: 31004
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: flask-app
  type: NodePort 

