apiVersion: v1
kind: Pod
metadata: 
  name: configmap-mysql-pod
spec:
  containers:
  - name: demo-mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:  
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: password
    - name: SECRET_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: rootPassword
    - name: DATABASE
      valueFrom:
        secretKeyRef:
          name: helloworld-secrets
          key: database